name: Swift

on: [push]

jobs:
    build:
        name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest]
                swift: ["5.10", "6.1"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: swift-actions/setup-swift@682457186b71c25a884c45c06f859febbe259240
              with:
                  swift-version: ${{ matrix.swift }}
            - uses: actions/checkout@v5
            - name: Build
              run: swift build
            - name: Run tests
              run: swift test
